server:
  address: ":8080"
  timeout: 4s
  idle_timeout: 60s
  shutdown_timeout: 10s
db:
  host: "postgres-service" #"localhost" 
  port: 5432
  username: "postgres"
  name: "image_processor"
  password: "postgres"

storage_path: "./storage"

kafka:
  brokers:
    - "kafka:9092"            
  topic: "images"
  group_id: "image_processor_group"
kafka_ui:
  enabled: true
  url: "http://localhost:8081" 
  cluster_name: "local"
  polling_timeout_ms: 30000